give:
  enabled: true
  worlds:
    - old_server
    - old_server_nether
    - old_server_the_end
    - parkour
  same-world-only: true
  to-self-only: false
  forbidden:
    - command_block
    - repeating_command_block
    - chain_command_block
    - Owner
  strict: true

teleport:
  enabled: true
  worlds:
    - old_server
    - old_server_nether
    - old_server_the_end
    - parkour
  same-world-only: false
  involve-self-only: true

gamemode:
  enabled: true
  worlds:
    - old_server
    - old_server_nether
    - old_server_the_end
    - parkour
  same-world-only: false
  involve-self-only: false

multiverse:
  enabled: true
  block-worlds:
    - examplenether
  block-player-tp: true

transfer:
  enabled: true
  block-other-players: true

summon:
  enabled: true
  forbidden:
    - command_block_minecart
    - falling_block
  strict-find: true

settitle:
  enabled: true
  allowed:
    - written_book
    - writable_book

setlore:
  enabled: true
  allowed:
    - written_book
    - writable_book

parkour:
  enabled: true
  blocked-regexes:
    - setcourse \S+ command

whitelist-commands:
  #These commands will be ignored and not processed
  - tpcancel
  - tpaccept
  - tpdeny

tpa:
  enabled: true
  #Will be blocked if both source and target are not in allowed world
  allowed-worlds:
    - survival
    - survival-end
    - survival-nether

enchant:
  enabled: true
  allowed-worlds:
    - old_server
    - old_server_nether
    - old_server_the_end

attribute:
  enabled: true
  allowed-worlds:
    - old_server
    - old_server_nether
    - old_server_the_end

settings:
  #Overall plugin settings
  print-traceback: false
  #Will the plugin print the full traceback if the processor fails?
  note-intercept: false
  #Will the plugin log when it intercepts a command, pass or fail?
  note-alert: true
  #Will the plugin log when it catches someone trying to abuse?